# Generated by Django 5.2.1 on 2025-05-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField(unique=True)),
                ('datetime', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('scrape_economic_times', 'Scrape Economic Times')], max_length=100, unique=True)),
                ('interval_minutes', models.PositiveIntegerField(default=5)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
