# Generated by Django 5.2.1 on 2025-05-28 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduledTask',
        ),
    ]
