FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN apt-get update && apt-get install -y dos2unix bash

COPY backend/requirements.txt /app/
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY backend /app/

RUN chmod +x /app/entrypoint.sh && dos2unix /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]