# Generated by Django 5.2.1 on 2025-05-28 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scrapy', '0002_delete_scheduledtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('source', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('tags', models.JSONField()),
                ('news_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapy.newsstory')),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('symbol', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('confidence', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('news_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapy.newsstory')),
            ],
        ),
    ]
