# Generated by Django 5.2.1 on 2025-05-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('entry', 'Entry')], max_length=10),
        ),
    ]
